spring:
  application:
    name: vestimentas-eden


  datasource:
    url: ${BMS_DATABASE_URL:jdbc:postgresql://localhost:5432/vestimentas_db}
    username: ${BMS_DATABASE_USERNAME:vestimentas_user}
    password: ${BMS_DATABASE_PASSWORD:eden_password}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate
